image:
  file: .gitpod.Dockerfile
  
vscode:
  extensions:
    - Ikuyadeu.r@1.2.1:z5vr1v1bfS++U/aHLSXQ6Q==

tasks:
  - name: Setup R libs and Run
    init: |
      sudo apt-get install libxml2-dev
    command: R CMD BATCH test.r && cat test.r.Rout
    